spring.datasource.url=${JDBC_DATABASE_URL:${DATABASE_URL}}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${PGUSER:${DATABASE_USERNAME:}}
spring.datasource.password=${PGPASSWORD:${DATABASE_PASSWORD:}}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server.port=${PORT:8080}
